// Usings sit above the namespace declaration on purpose. RainWorldSaveManager.Core.System
// exists elsewhere in this assembly, so a using written inside the namespace body would bind
// "System" to that namespace instead of the BCL root.

namespace RainWorldSaveManager.Core.Saves;

/// <summary>
/// The data pearls the game knows, with the colour it paints each one and whether it carries
/// lore rather than being a generic pickup.
///
/// The table was generated by loading the game assembly and calling DataPearl.UniquePearlMainColor
/// and DataPearl.PearlIsNotMisc for every registered DataPearlType, rather than transcribed by
/// hand, so the colours are the ones the game actually uses. Regenerate it the same way if a
/// game update adds pearls.
/// </summary>
public static class PearlCatalog
{
    /// <summary>What one pearl type looks like and whether reading it gives lore.</summary>
    /// <param name="Id">The stored DataPearlType name, for example SL_moon.</param>
    /// <param name="ColorHex">The colour the game paints it, as #RRGGBB.</param>
    /// <param name="IsLore">False for the generic Misc, Misc2 and BroadcastMisc pickups.</param>
    public sealed record PearlInfo(string Id, string ColorHex, bool IsLore);

    private static readonly Dictionary<string, PearlInfo> ById =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["Misc"] = new("Misc", "#000000", false),
            ["Misc2"] = new("Misc2", "#000000", false),
            ["CC"] = new("CC", "#E5991A", true),
            ["SI_west"] = new("SI_west", "#030303", true),
            ["SI_top"] = new("SI_top", "#030303", true),
            ["LF_west"] = new("LF_west", "#FF004D", true),
            ["LF_bottom"] = new("LF_bottom", "#FF1A1A", true),
            ["HI"] = new("HI", "#0232FF", true),
            ["SH"] = new("SH", "#33001A", true),
            ["DS"] = new("DS", "#00B21A", true),
            ["SB_filtration"] = new("SB_filtration", "#1A8080", true),
            ["SB_ravine"] = new("SB_ravine", "#030303", true),
            ["GW"] = new("GW", "#00B280", true),
            ["SL_bridge"] = new("SL_bridge", "#661AE5", true),
            ["SL_moon"] = new("SL_moon", "#E5F233", true),
            ["SU"] = new("SU", "#8099E5", true),
            ["UW"] = new("UW", "#669966", true),
            ["PebblesPearl"] = new("PebblesPearl", "#000000", false),
            ["SL_chimney"] = new("SL_chimney", "#FF008C", true),
            ["Red_stomach"] = new("Red_stomach", "#99FFE5", true),
            ["Spearmasterpearl"] = new("Spearmasterpearl", "#0A030A", true),
            ["SU_filt"] = new("SU_filt", "#FFBFE5", true),
            ["SI_chat3"] = new("SI_chat3", "#030303", true),
            ["SI_chat4"] = new("SI_chat4", "#030303", true),
            ["SI_chat5"] = new("SI_chat5", "#030303", true),
            ["DM"] = new("DM", "#F4EB35", true),
            ["LC"] = new("LC", "#006604", true),
            ["OE"] = new("OE", "#8C5ECC", true),
            ["MS"] = new("MS", "#D0E445", true),
            ["RM"] = new("RM", "#622FFB", true),
            ["Rivulet_stomach"] = new("Rivulet_stomach", "#96DEA0", true),
            ["LC_second"] = new("LC_second", "#990000", true),
            ["CL"] = new("CL", "#7C49FF", true),
            ["VS"] = new("VS", "#870DEB", true),
            ["BroadcastMisc"] = new("BroadcastMisc", "#E5B2CC", false),
            ["WORA"] = new("WORA", "#8FD647", true),
            ["WAUA"] = new("WAUA", "#F2331A", true),
            ["DRONE"] = new("DRONE", "#E5B280", true),
            ["ABSTRACT"] = new("ABSTRACT", "#007373", true),
            ["AUDIO_VOICEWIND1"] = new("AUDIO_VOICEWIND1", "#762DCB", true),
            ["AUDIO_VOICEWIND2"] = new("AUDIO_VOICEWIND2", "#7934C9", true),
            ["AUDIO_JAM1"] = new("AUDIO_JAM1", "#6C40F2", true),
            ["AUDIO_JAM2"] = new("AUDIO_JAM2", "#7249EC", true),
            ["AUDIO_JAM3"] = new("AUDIO_JAM3", "#683AF5", true),
            ["AUDIO_JAM4"] = new("AUDIO_JAM4", "#6636F7", true),
            ["AUDIO_GROOVE"] = new("AUDIO_GROOVE", "#7045EF", true),
            ["TEXT_AUDIO_TALKSHOW"] = new("TEXT_AUDIO_TALKSHOW", "#CC14A6", true),
            ["TEXT_NOTIONOFSELF"] = new("TEXT_NOTIONOFSELF", "#66BF66", true),
            ["TEXT_SECRET"] = new("TEXT_SECRET", "#803399", true),
            ["TEXT_CONTEMPT"] = new("TEXT_CONTEMPT", "#BD7A8A", true),
            ["TEXT_STARDUST"] = new("TEXT_STARDUST", "#59E5A6", true),
            ["TEXT_KITESDAY"] = new("TEXT_KITESDAY", "#F2A605", true),
        };

    /// <summary>Every pearl the table knows, in the order the game registers them.</summary>
    public static IReadOnlyCollection<PearlInfo> All => ById.Values;

    /// <summary>
    /// The pearl with this stored id, or null when the save names one this table does not know,
    /// which is what a pearl added by another mod looks like.
    /// </summary>
    public static PearlInfo? ForId(string? pearlId)
    {
        if (string.IsNullOrWhiteSpace(pearlId))
        {
            return null;
        }

        return ById.TryGetValue(pearlId.Trim(), out PearlInfo? info) ? info : null;
    }
}

